repos:
  - repo: local
    hooks:
      - id: commitizen
        name: Check Conventional Commit
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
